-- Carga los departamentos y carreras de Ciencias Contables (ID_EDIFICIO = 2).
-- Es seguro correrlo mas de una vez: si un departamento ya existe (por
-- nombre), no lo vuelve a insertar.

BEGIN
    DECLARE @id_dep INTEGER;
    DECLARE @id_carrera INTEGER;

    IF NOT EXISTS (SELECT 1 FROM DBA.DEPARTAMENTOS WHERE NOMBRE = 'DCC - Ciencias Contables') THEN
        SELECT COALESCE(MAX(ID_DEPARTAMENTO), 0) + 1 INTO @id_dep FROM DBA.DEPARTAMENTOS;
        SELECT COALESCE(MAX(ID_CARRERA), 0) + 1 INTO @id_carrera FROM DBA.CARRERAS;
        INSERT INTO DBA.DEPARTAMENTOS (ID_DEPARTAMENTO, ID_EDIFICIO, NOMBRE) VALUES (@id_dep, 2, 'DCC - Ciencias Contables');
        INSERT INTO DBA.CARRERAS (ID_CARRERA, ID_DEPARTAMENTO, NOMBRE) VALUES (@id_carrera, @id_dep, 'Ciencias Contables');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM DBA.DEPARTAMENTOS WHERE NOMBRE = 'DECO - Economia') THEN
        SELECT COALESCE(MAX(ID_DEPARTAMENTO), 0) + 1 INTO @id_dep FROM DBA.DEPARTAMENTOS;
        SELECT COALESCE(MAX(ID_CARRERA), 0) + 1 INTO @id_carrera FROM DBA.CARRERAS;
        INSERT INTO DBA.DEPARTAMENTOS (ID_DEPARTAMENTO, ID_EDIFICIO, NOMBRE) VALUES (@id_dep, 2, 'DECO - Economia');
        INSERT INTO DBA.CARRERAS (ID_CARRERA, ID_DEPARTAMENTO, NOMBRE) VALUES (@id_carrera, @id_dep, 'Economia');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM DBA.DEPARTAMENTOS WHERE NOMBRE = 'DMK - Marketing') THEN
        SELECT COALESCE(MAX(ID_DEPARTAMENTO), 0) + 1 INTO @id_dep FROM DBA.DEPARTAMENTOS;
        SELECT COALESCE(MAX(ID_CARRERA), 0) + 1 INTO @id_carrera FROM DBA.CARRERAS;
        INSERT INTO DBA.DEPARTAMENTOS (ID_DEPARTAMENTO, ID_EDIFICIO, NOMBRE) VALUES (@id_dep, 2, 'DMK - Marketing');
        INSERT INTO DBA.CARRERAS (ID_CARRERA, ID_DEPARTAMENTO, NOMBRE) VALUES (@id_carrera, @id_dep, 'Marketing');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM DBA.DEPARTAMENTOS WHERE NOMBRE = 'DADE - Administracion de Empresas') THEN
        SELECT COALESCE(MAX(ID_DEPARTAMENTO), 0) + 1 INTO @id_dep FROM DBA.DEPARTAMENTOS;
        SELECT COALESCE(MAX(ID_CARRERA), 0) + 1 INTO @id_carrera FROM DBA.CARRERAS;
        INSERT INTO DBA.DEPARTAMENTOS (ID_DEPARTAMENTO, ID_EDIFICIO, NOMBRE) VALUES (@id_dep, 2, 'DADE - Administracion de Empresas');
        INSERT INTO DBA.CARRERAS (ID_CARRERA, ID_DEPARTAMENTO, NOMBRE) VALUES (@id_carrera, @id_dep, 'Administracion de Empresas');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM DBA.DEPARTAMENTOS WHERE NOMBRE = 'DCI - Comercio Internacional') THEN
        SELECT COALESCE(MAX(ID_DEPARTAMENTO), 0) + 1 INTO @id_dep FROM DBA.DEPARTAMENTOS;
        SELECT COALESCE(MAX(ID_CARRERA), 0) + 1 INTO @id_carrera FROM DBA.CARRERAS;
        INSERT INTO DBA.DEPARTAMENTOS (ID_DEPARTAMENTO, ID_EDIFICIO, NOMBRE) VALUES (@id_dep, 2, 'DCI - Comercio Internacional');
        INSERT INTO DBA.CARRERAS (ID_CARRERA, ID_DEPARTAMENTO, NOMBRE) VALUES (@id_carrera, @id_dep, 'Comercio Internacional');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM DBA.DEPARTAMENTOS WHERE NOMBRE = 'DENF - Enfermeria') THEN
        SELECT COALESCE(MAX(ID_DEPARTAMENTO), 0) + 1 INTO @id_dep FROM DBA.DEPARTAMENTOS;
        SELECT COALESCE(MAX(ID_CARRERA), 0) + 1 INTO @id_carrera FROM DBA.CARRERAS;
        INSERT INTO DBA.DEPARTAMENTOS (ID_DEPARTAMENTO, ID_EDIFICIO, NOMBRE) VALUES (@id_dep, 2, 'DENF - Enfermeria');
        INSERT INTO DBA.CARRERAS (ID_CARRERA, ID_DEPARTAMENTO, NOMBRE) VALUES (@id_carrera, @id_dep, 'Enfermeria');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM DBA.DEPARTAMENTOS WHERE NOMBRE = 'DFON - Fonoaudiologia') THEN
        SELECT COALESCE(MAX(ID_DEPARTAMENTO), 0) + 1 INTO @id_dep FROM DBA.DEPARTAMENTOS;
        SELECT COALESCE(MAX(ID_CARRERA), 0) + 1 INTO @id_carrera FROM DBA.CARRERAS;
        INSERT INTO DBA.DEPARTAMENTOS (ID_DEPARTAMENTO, ID_EDIFICIO, NOMBRE) VALUES (@id_dep, 2, 'DFON - Fonoaudiologia');
        INSERT INTO DBA.CARRERAS (ID_CARRERA, ID_DEPARTAMENTO, NOMBRE) VALUES (@id_carrera, @id_dep, 'Fonoaudiologia');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM DBA.DEPARTAMENTOS WHERE NOMBRE = 'DMED - Medicina') THEN
        SELECT COALESCE(MAX(ID_DEPARTAMENTO), 0) + 1 INTO @id_dep FROM DBA.DEPARTAMENTOS;
        SELECT COALESCE(MAX(ID_CARRERA), 0) + 1 INTO @id_carrera FROM DBA.CARRERAS;
        INSERT INTO DBA.DEPARTAMENTOS (ID_DEPARTAMENTO, ID_EDIFICIO, NOMBRE) VALUES (@id_dep, 2, 'DMED - Medicina');
        INSERT INTO DBA.CARRERAS (ID_CARRERA, ID_DEPARTAMENTO, NOMBRE) VALUES (@id_carrera, @id_dep, 'Medicina');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM DBA.DEPARTAMENTOS WHERE NOMBRE = 'DNUT - Nutricion') THEN
        SELECT COALESCE(MAX(ID_DEPARTAMENTO), 0) + 1 INTO @id_dep FROM DBA.DEPARTAMENTOS;
        SELECT COALESCE(MAX(ID_CARRERA), 0) + 1 INTO @id_carrera FROM DBA.CARRERAS;
        INSERT INTO DBA.DEPARTAMENTOS (ID_DEPARTAMENTO, ID_EDIFICIO, NOMBRE) VALUES (@id_dep, 2, 'DNUT - Nutricion');
        INSERT INTO DBA.CARRERAS (ID_CARRERA, ID_DEPARTAMENTO, NOMBRE) VALUES (@id_carrera, @id_dep, 'Nutricion');
    END IF;

    COMMIT;
END
